prod:     'www.sumdog.com'
dev:      'localhost'
test-cc:  'test-cc.sumdog.com'
test-djp: 'test-djp.sumdog.com'
test-dp:  'test-dp.sumdog.com'
test-dw:  'test-dw.sumdog.com'
test-gm:  'test-gm.sumdog.com'
test-gs:  'test-gs.sumdog.com'
test-kh:  'test-kh.sumdog.com'
test-pb:  'test-pb.sumdog.com'
test-sr:  'test-sr.sumdog.com'
test-tl:  'test-tl.sumdog.com'
test-1:   'test-1.sumdog.com'
test-2:   'test-2.sumdog.com'
